name: CI / Quality Check

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint-build-test:
    name: Build & Test Microservices
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: auth_db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mongodb:
        image: mongo:7.0
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: mongo_password
        ports:
          - 27017:27017

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Monorepo Dependencies
        run: npm ci

      - name: Compile TypeScript (`tsc`)
        run: npm run build

      - name: Execute Tests & Coverage
        env:
          DATABASE_URL: postgresql://postgres:postgres_password@localhost:5432/auth_db_test?schema=public
          MONGO_URI: mongodb://admin:mongo_password@localhost:27017/orders_db_test?authSource=admin
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          JWT_SECRET: ci_jwt_secret_token_key_testing_12345
        run: npm run test
